<?php

/**
 * This is the model base class for the table "direccion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Direccion".
 *
 * Columns in table "direccion" available as properties of the model,
 * followed by relations of table "direccion" available as properties of the model.
 *
 * @property integer $id
 * @property string $calle_1
 * @property string $calle_2
 * @property string $numero
 * @property string $codigo_postal
 * @property string $referencia
 * @property string $latitud
 * @property string $longitud
 * @property integer $barrio_id
 * @property integer $parroquia_id
 *
 * @property Agencia[] $agencias
 * @property Barrio $barrio
 * @property Parroquia $parroquia
 * @property Persona[] $personas
 * @property Sucursal[] $sucursals
 */
abstract class BaseDireccion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'direccion';
    }

    public static function representingColumn() {
        return 'calle_1';
    }

    public function rules() {
        return array(
            array('parroquia_id', 'required'),
            array('barrio_id, parroquia_id', 'numerical', 'integerOnly'=>true),
            array('calle_1, calle_2, numero, codigo_postal', 'length', 'max'=>45),
            array('latitud, longitud', 'length', 'max'=>60),
            array('referencia', 'safe'),
            array('calle_1, calle_2, numero, codigo_postal, referencia, latitud, longitud, barrio_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, calle_1, calle_2, numero, codigo_postal, referencia, latitud, longitud, barrio_id, parroquia_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'agencias' => array(self::HAS_MANY, 'Agencia', 'direccion_id'),
            'barrio' => array(self::BELONGS_TO, 'Barrio', 'barrio_id'),
            'parroquia' => array(self::BELONGS_TO, 'Parroquia', 'parroquia_id'),
            'personas' => array(self::HAS_MANY, 'Persona', 'direccion_id'),
            'sucursals' => array(self::HAS_MANY, 'Sucursal', 'direccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'calle_1' => Yii::t('app', 'Calle 1'),
                'calle_2' => Yii::t('app', 'Calle 2'),
                'numero' => Yii::t('app', 'Numero'),
                'codigo_postal' => Yii::t('app', 'Codigo Postal'),
                'referencia' => Yii::t('app', 'Referencia'),
                'latitud' => Yii::t('app', 'Latitud'),
                'longitud' => Yii::t('app', 'Longitud'),
                'barrio_id' => Yii::t('app', 'Barrio'),
                'parroquia_id' => Yii::t('app', 'Parroquia'),
                'agencias' => null,
                'barrio' => null,
                'parroquia' => null,
                'personas' => null,
                'sucursals' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('calle_1', $this->calle_1, true);
        $criteria->compare('calle_2', $this->calle_2, true);
        $criteria->compare('numero', $this->numero, true);
        $criteria->compare('codigo_postal', $this->codigo_postal, true);
        $criteria->compare('referencia', $this->referencia, true);
        $criteria->compare('latitud', $this->latitud, true);
        $criteria->compare('longitud', $this->longitud, true);
        $criteria->compare('barrio_id', $this->barrio_id);
        $criteria->compare('parroquia_id', $this->parroquia_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}