<?php

/**
 * This is the model base class for the table "sucursal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sucursal".
 *
 * Columns in table "sucursal" available as properties of the model,
 * followed by relations of table "sucursal" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $email
 * @property string $estado
 * @property integer $agencia_id
 * @property integer $direccion_id
 *
 * @property Agencia $agencia
 * @property Direccion $direccion
 */
abstract class BaseSucursal extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'sucursal';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, estado, agencia_id, direccion_id', 'required'),
            array('agencia_id, direccion_id', 'numerical', 'integerOnly'=>true),
            array('email', 'email'),
            array('nombre', 'length', 'max'=>45),
            array('email', 'length', 'max'=>50),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('email', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, email, estado, agencia_id, direccion_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'agencia' => array(self::BELONGS_TO, 'Agencia', 'agencia_id'),
            'direccion' => array(self::BELONGS_TO, 'Direccion', 'direccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'email' => Yii::t('app', 'Email'),
                'estado' => Yii::t('app', 'Estado'),
                'agencia_id' => Yii::t('app', 'Agencia'),
                'direccion_id' => Yii::t('app', 'Direccion'),
                'agencia' => null,
                'direccion' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('agencia_id', $this->agencia_id);
        $criteria->compare('direccion_id', $this->direccion_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}