<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombres
 * @property string $apellidos
 * @property string $cedula
 * @property string $ruc
 * @property integer $direccion_id
 *
 * @property Direccion $direccion
 */
abstract class BaseCliente extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cliente';
    }

    public static function representingColumn() {
        return 'cedula';
    }

    public function rules() {
        return array(
            array('cedula', 'required'),
            array('direccion_id', 'numerical', 'integerOnly'=>true),
            array('nombres, apellidos, cedula, ruc', 'length', 'max'=>45),
            array('nombres, apellidos, ruc, direccion_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombres, apellidos, cedula, ruc, direccion_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'direccion' => array(self::BELONGS_TO, 'Direccion', 'direccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombres' => Yii::t('app', 'Nombres'),
                'apellidos' => Yii::t('app', 'Apellidos'),
                'cedula' => Yii::t('app', 'Cedula'),
                'ruc' => Yii::t('app', 'Ruc'),
                'direccion_id' => Yii::t('app', 'Direccion'),
                'direccion' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombres', $this->nombres, true);
        $criteria->compare('apellidos', $this->apellidos, true);
        $criteria->compare('cedula', $this->cedula, true);
        $criteria->compare('ruc', $this->ruc, true);
        $criteria->compare('direccion_id', $this->direccion_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}