<?php

/**
 * This is the model base class for the table "trayectoria_producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TrayectoriaProducto".
 *
 * Columns in table "trayectoria_producto" available as properties of the model,
 * followed by relations of table "trayectoria_producto" available as properties of the model.
 *
 * @property integer $id
 * @property integer $trayectoria_id
 * @property integer $producto_id
 * @property integer $cliente_origen_id
 * @property integer $cliente_destino_id
 * @property integer $ciudad_origen_id
 * @property integer $ciudad_destino_id
 * @property string $fecha_creacion
 * @property string $fecha_enviado
 * @property string $estado
 *
 * @property Trayectoria $trayectoria
 */
abstract class BaseTrayectoriaProducto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'trayectoria_producto';
    }

    public static function representingColumn() {
        return 'fecha_creacion';
    }

    public function rules() {
        return array(
            array('trayectoria_id, producto_id, cliente_origen_id, cliente_destino_id, ciudad_origen_id, ciudad_destino_id', 'required'),
            array('trayectoria_id, producto_id, cliente_origen_id, cliente_destino_id, ciudad_origen_id, ciudad_destino_id', 'numerical', 'integerOnly'=>true),
            array('estado', 'length', 'max'=>9),
            array('fecha_enviado', 'safe'),
            array('estado', 'in', 'range' => array('EN ESPERA','ENVIADO')), // enum,
            array('fecha_enviado, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, trayectoria_id, producto_id, cliente_origen_id, cliente_destino_id, ciudad_origen_id, ciudad_destino_id, fecha_creacion, fecha_enviado, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'trayectoria' => array(self::BELONGS_TO, 'Trayectoria', 'trayectoria_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'trayectoria_id' => Yii::t('app', 'Trayectoria'),
                'producto_id' => Yii::t('app', 'Producto'),
                'cliente_origen_id' => Yii::t('app', 'Cliente Origen'),
                'cliente_destino_id' => Yii::t('app', 'Cliente Destino'),
                'ciudad_origen_id' => Yii::t('app', 'Ciudad Origen'),
                'ciudad_destino_id' => Yii::t('app', 'Ciudad Destino'),
                'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
                'fecha_enviado' => Yii::t('app', 'Fecha Enviado'),
                'estado' => Yii::t('app', 'Estado'),
                'trayectoria' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('trayectoria_id', $this->trayectoria_id);
        $criteria->compare('producto_id', $this->producto_id);
        $criteria->compare('cliente_origen_id', $this->cliente_origen_id);
        $criteria->compare('cliente_destino_id', $this->cliente_destino_id);
        $criteria->compare('ciudad_origen_id', $this->ciudad_origen_id);
        $criteria->compare('ciudad_destino_id', $this->ciudad_destino_id);
        $criteria->compare('fecha_creacion', $this->fecha_creacion, true);
        $criteria->compare('fecha_enviado', $this->fecha_enviado, true);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'CTimestampBehavior' => array(
                'class' => 'zii.behaviors.CTimestampBehavior',
                'createAttribute' => 'fecha_creacion',
                'updateAttribute' => null,
                'timestampExpression' => new CDbExpression('NOW()'),
            )
        ), parent::behaviors());
    }
}