<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * followed by relations of table "producto" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $peso
 * @property string $precio_principal
 * @property string $precio_secundario
 * @property string $precio_especial
 * @property integer $producto_categoria_id
 *
 * @property ProductoCategoria $productoCategoria
 */
abstract class BaseProducto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'producto';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, peso, precio_principal, precio_secundario, precio_especial, producto_categoria_id', 'required'),
            array('peso, producto_categoria_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('precio_principal, precio_secundario, precio_especial', 'length', 'max'=>10),
            array('id, nombre, peso, precio_principal, precio_secundario, precio_especial, producto_categoria_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'productoCategoria' => array(self::BELONGS_TO, 'ProductoCategoria', 'producto_categoria_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'peso' => Yii::t('app', 'Peso'),
                'precio_principal' => Yii::t('app', 'Precio Principal'),
                'precio_secundario' => Yii::t('app', 'Precio Secundario'),
                'precio_especial' => Yii::t('app', 'Precio Especial'),
                'producto_categoria_id' => Yii::t('app', 'Producto Categoria'),
                'productoCategoria' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('peso', $this->peso);
        $criteria->compare('precio_principal', $this->precio_principal, true);
        $criteria->compare('precio_secundario', $this->precio_secundario, true);
        $criteria->compare('precio_especial', $this->precio_especial, true);
        $criteria->compare('producto_categoria_id', $this->producto_categoria_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}