<?php

/**
 * This is the model base class for the table "telefono".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Telefono".
 *
 * Columns in table "telefono" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $numero
 * @property string $estado
 * @property integer $principal
 * @property string $tipo
 * @property string $entidad_tipo
 * @property integer $entidad_id
 *
 */
abstract class BaseTelefono extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'telefono';
    }

    public static function representingColumn() {
        return 'numero';
    }

    public function rules() {
        return array(
            array('numero, estado, principal, tipo, entidad_tipo, entidad_id', 'required'),
            array('principal, entidad_id', 'numerical', 'integerOnly'=>true),
            array('numero, estado', 'length', 'max'=>45),
            array('tipo', 'length', 'max'=>8),
            array('entidad_tipo', 'length', 'max'=>12),
            array('tipo', 'in', 'range' => array('PERSONA','AGENCIA','SUCURSAL')), // enum,
            array('entidad_tipo', 'in', 'range' => array('CELULAR','CONVENCIONAL')), // enum,
            array('id, numero, estado, principal, tipo, entidad_tipo, entidad_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'numero' => Yii::t('app', 'Numero'),
                'estado' => Yii::t('app', 'Estado'),
                'principal' => Yii::t('app', 'Principal'),
                'tipo' => Yii::t('app', 'Tipo'),
                'entidad_tipo' => Yii::t('app', 'Entidad Tipo'),
                'entidad_id' => Yii::t('app', 'Entidad'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('numero', $this->numero, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('principal', $this->principal);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('entidad_tipo', $this->entidad_tipo, true);
        $criteria->compare('entidad_id', $this->entidad_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}