<?php

/**
 * This is the model base class for the table "ciudad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ciudad".
 *
 * Columns in table "ciudad" available as properties of the model,
 * followed by relations of table "ciudad" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $estado
 * @property string $tipo
 * @property integer $provincia_id
 *
 * @property Provincia $provincia
 * @property Parroquia[] $parroquias
 */
abstract class BaseCiudad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ciudad';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, estado, tipo, provincia_id', 'required'),
            array('provincia_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('tipo', 'length', 'max'=>17),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('tipo', 'in', 'range' => array('PRINCIPAL','SECUNDARIA','TRAYECTO ESPECIAL')), // enum,
            array('id, nombre, estado, tipo, provincia_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'provincia' => array(self::BELONGS_TO, 'Provincia', 'provincia_id'),
            'parroquias' => array(self::HAS_MANY, 'Parroquia', 'ciudad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'estado' => Yii::t('app', 'Estado'),
                'tipo' => Yii::t('app', 'Tipo'),
                'provincia_id' => Yii::t('app', 'Provincia'),
                'provincia' => null,
                'parroquias' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('provincia_id', $this->provincia_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}