<?php

/**
 * This is the model base class for the table "trayectoria_checkpoint".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TrayectoriaCheckpoint".
 *
 * Columns in table "trayectoria_checkpoint" available as properties of the model,
 * followed by relations of table "trayectoria_checkpoint" available as properties of the model.
 *
 * @property integer $id
 * @property string $estado
 * @property integer $ciudad_id
 * @property integer $usuario_actualizacion_id
 * @property string $fecha_actualizacion_id
 * @property integer $trayectoria_id
 * @property string $observaciones
 *
 * @property Trayectoria $trayectoria
 */
abstract class BaseTrayectoriaCheckpoint extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'trayectoria_checkpoint';
    }

    public static function representingColumn() {
        return 'estado';
    }

    public function rules() {
        return array(
            array('estado, ciudad_id, usuario_actualizacion_id, fecha_actualizacion_id, trayectoria_id', 'required'),
            array('ciudad_id, usuario_actualizacion_id, trayectoria_id', 'numerical', 'integerOnly'=>true),
            array('estado', 'length', 'max'=>9),
            array('observaciones', 'safe'),
            array('estado', 'in', 'range' => array('EN ESPERA','APROBADO')), // enum,
            array('observaciones', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, estado, ciudad_id, usuario_actualizacion_id, fecha_actualizacion_id, trayectoria_id, observaciones', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'trayectoria' => array(self::BELONGS_TO, 'Trayectoria', 'trayectoria_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'estado' => Yii::t('app', 'Estado'),
                'ciudad_id' => Yii::t('app', 'Ciudad'),
                'usuario_actualizacion_id' => Yii::t('app', 'Usuario Actualizacion'),
                'fecha_actualizacion_id' => Yii::t('app', 'Fecha Actualizacion'),
                'trayectoria_id' => Yii::t('app', 'Trayectoria'),
                'observaciones' => Yii::t('app', 'Observaciones'),
                'trayectoria' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('ciudad_id', $this->ciudad_id);
        $criteria->compare('usuario_actualizacion_id', $this->usuario_actualizacion_id);
        $criteria->compare('fecha_actualizacion_id', $this->fecha_actualizacion_id, true);
        $criteria->compare('trayectoria_id', $this->trayectoria_id);
        $criteria->compare('observaciones', $this->observaciones, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}